---
title: Slides nd Additional Materials
---

Each class session is accompanied by a set of slides that will guide the lecture portion of the lesson. These slides are essential to follow along during the session and will be the primary resource used for instruction. You should review the slides before participating in the session to get the most out of the lecture.

While the slides are the central resource for each session, I might also share additional materials or resources that could be relevant to the specific topics covered. These may include readings, articles, or supplementary videos, which will be made available as needed.

For each session throughout the math camp, you'll find the lecture slides embedded directly on the session page. You can view them in your browser or download them as a PDF for offline use:

<p class="buttons" style="text-align:center;"><span class="btn btn-danger">{{< fa arrow-up-right-from-square >}} View all slides in new window</span> <span class="btn btn-danger">{{< fa file-pdf >}} Download PDF of all slides</span></p>
The slides can be navigated using your keyboard with <kbd>←</kbd> and <kbd>→</kbd> for moving through the presentation. If you press <kbd>?</kbd> (or <kbd>shift</kbd> + <kbd>/</kbd>), you'll see a list of commands for interacting with the slides, including options for fullscreen mode (<kbd>f</kbd>) or presenter mode (<kbd>p</kbd>), which displays additional notes.